/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SocietyRouteImport } from './routes/society'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthAppReturnRouteImport } from './routes/auth/app-return'
import { Route as AuthAppStartRouteImport } from './routes/auth/app-start'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronSyncStockRouteImport } from './routes/api/cron/sync-stock'
import { Route as ApiWebhooksDropshipRouteImport } from './routes/api/webhooks/dropship'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietyRoute = SocietyRouteImport.update({
  id: '/society',
  path: '/society',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppReturnRoute = AuthAppReturnRouteImport.update({
  id: '/auth/app-return',
  path: '/auth/app-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppStartRoute = AuthAppStartRouteImport.update({
  id: '/auth/app-start',
  path: '/auth/app-start',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncStockRoute = ApiCronSyncStockRouteImport.update({
  id: '/api/cron/sync-stock',
  path: '/api/cron/sync-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksDropshipRoute = ApiWebhooksDropshipRouteImport.update({
  id: '/api/webhooks/dropship',
  path: '/api/webhooks/dropship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/society': typeof SocietyRoute
  '/terms': typeof TermsRoute
  '/auth/app-return': typeof AuthAppReturnRoute
  '/auth/app-start': typeof AuthAppStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-stock': typeof ApiCronSyncStockRoute
  '/api/webhooks/dropship': typeof ApiWebhooksDropshipRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/society': typeof SocietyRoute
  '/terms': typeof TermsRoute
  '/auth/app-return': typeof AuthAppReturnRoute
  '/auth/app-start': typeof AuthAppStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-stock': typeof ApiCronSyncStockRoute
  '/api/webhooks/dropship': typeof ApiWebhooksDropshipRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/society': typeof SocietyRoute
  '/terms': typeof TermsRoute
  '/auth/app-return': typeof AuthAppReturnRoute
  '/auth/app-start': typeof AuthAppStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-stock': typeof ApiCronSyncStockRoute
  '/api/webhooks/dropship': typeof ApiWebhooksDropshipRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/society'
    | '/terms'
    | '/auth/app-return'
    | '/auth/app-start'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/cron/sync-stock'
    | '/api/webhooks/dropship'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/society'
    | '/terms'
    | '/auth/app-return'
    | '/auth/app-start'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/cron/sync-stock'
    | '/api/webhooks/dropship'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/society'
    | '/terms'
    | '/auth/app-return'
    | '/auth/app-start'
    | '/checkout/success'
    | '/api/auth/$'
    | '/api/cron/sync-stock'
    | '/api/webhooks/dropship'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SocietyRoute: typeof SocietyRoute
  TermsRoute: typeof TermsRoute
  AuthAppReturnRoute: typeof AuthAppReturnRoute
  AuthAppStartRoute: typeof AuthAppStartRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncStockRoute: typeof ApiCronSyncStockRoute
  ApiWebhooksDropshipRoute: typeof ApiWebhooksDropshipRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/society': {
      id: '/society'
      path: '/society'
      fullPath: '/society'
      preLoaderRoute: typeof SocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/app-return': {
      id: '/auth/app-return'
      path: '/auth/app-return'
      fullPath: '/auth/app-return'
      preLoaderRoute: typeof AuthAppReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/app-start': {
      id: '/auth/app-start'
      path: '/auth/app-start'
      fullPath: '/auth/app-start'
      preLoaderRoute: typeof AuthAppStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-stock': {
      id: '/api/cron/sync-stock'
      path: '/api/cron/sync-stock'
      fullPath: '/api/cron/sync-stock'
      preLoaderRoute: typeof ApiCronSyncStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/dropship': {
      id: '/api/webhooks/dropship'
      path: '/api/webhooks/dropship'
      fullPath: '/api/webhooks/dropship'
      preLoaderRoute: typeof ApiWebhooksDropshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SocietyRoute: SocietyRoute,
  TermsRoute: TermsRoute,
  AuthAppReturnRoute: AuthAppReturnRoute,
  AuthAppStartRoute: AuthAppStartRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncStockRoute: ApiCronSyncStockRoute,
  ApiWebhooksDropshipRoute: ApiWebhooksDropshipRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
